[build-system]
requires = ["setuptools>=46.1.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "sbr-generator/src/sbr/_version.py"
root = "."
relative_to = "__file__"
version_scheme = "guess-next-dev"
