spring:
  profiles:
    active: "dev"
  thymeleaf:
    prefix: classpath:/templates/
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: DETECT
server:
  servlet:
    context-path: {{project.restPath}}/{{project.version}}
---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:/tmp/{{project.name}}/sbr-gen-database.h2;DB_CLOSE_ON_EXIT=FALSE
    username: easin
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: False
debug: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
      boot:
        autoconfigure:
          logging: INFO
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: easin
    password:
    driverClassName: org.h2.Driver
    jpa:
      generate-ddl: true
      properties:
        hibernate:
          default_schema: public
          dialect: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop
      show-sql: true
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: False
debug: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG
      boot:
        autoconfigure:
          logging: INFO
---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/essDB
    username: easin
    password: Easin
    driverClassName: org.postgresql.Driver
    jpa:
      generate-ddl: true
      properties:
        hibernate:
          default_schema: public
          dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate:
        ddl-auto: none
      show-sql: true
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: False
